base = 'http://localhost:8000';
data = struct( ...
  'connector', 'local', ...
  'connector_config', struct('path', 'data/example.csv'), ...
  'query', struct('select', {{'date','series','value'}}, 'where', struct('series','GDP')) ...
);
opts = weboptions('MediaType','application/json');
resp = webwrite([base '/query'], data, opts);
disp(resp)